image: python:3.11

stages:
  - test

test:
  stage: test
  script:
    - git clone https://kumig.it/kumisystems/pix360.git project
    - cd project
    - pip install -Ur requirements.txt
    - pip install ..
    - python manage.py migrate
    - python manage.py test pix360_krpano